### ISSUE TITLE
Problems compiling using clang-1000.11.45.5 under MacOS X High Sierra

### ISSUE THREAD

**Issue by ciaccia** [mayerrn/HYPE#5]
Hi all,
I have tried to compile this project following the instruction you provided but for whatever reasons on my MacOSX running High Sierra it fails almost immediately. Nevertheless I managed to compile it using the command line g++ and I notice few problems.

1. the lambda functions in Partitioning.cpp fail because they cannot "resolve" the template type in the passed `reference_wrapper<const vector<Partition>>`. I managed to fix it by adding a `.get()` (see the attached patch)
2. the seed must be `uint32_t` instead of `int64_t` in Hypergraph class.
3. I replaced `boost::optional` with `std::optional` since you already target C++17
4. I removed some uneeded includes in "Hypergraph.cpp"

Attached to this post you find the patch containing the discussed fixes. 
Please let me know if you find the proposed changes useful.

Cheers

[patch.txt](https://github.com/mayerrn/HYPE/files/2591153/patch.txt)

**Comment by DarkWingMcQuack** [comment]
Hi @ciaccia,
Thanks for your feedback and the patch.

> the lambda functions in Partitioning.cpp fail because they cannot "resolve" the template type in the passed reference_wrapper<const vector<Partition>>. I managed to fix it by adding a .get() (see the attached patch)

This is actualy a problem we also have seen accross some different compilers. Depending on wether using `.get()` or not to unwrap the `std::reference_wrapper`s, different compilers accross different versions fail to compile the code. We decided to not use `.get()`, because that worked on GCC 7.3 and Clang 7.

> the seed must be uint32_t instead of int64_t in Hypergraph class.

Thanks a lot for mentioning this.

> I replaced boost::optional with std::optional since you already target C++17

I hightly appreciate this change, I only used `boost::optional` since when I wrote the code, my standard libary didn't support `std::optional`.

> I removed some uneeded includes in "Hypergraph.cpp"

Thanks for that as well.

Except for the annoying `.get()` problem with the reference wrappers, I will apply all your proposed changes. Thanks a lot for proposing the patch. If you want and have the time to, it would be nice if you could open a pull request with those changes. If not, I will shortly apply the changes myself and update everything.
Cheers, DarkWingMcQuack

**Comment by DarkWingMcQuack** [comment]
I applied the patch and some other changes. 
Thanks a lot

**Comment by ciaccia** [comment]
Hi @DarkWingMcQuack,
I understand the problem with the `wrapped_reference<>.get()`, I also noticed you had the version I proposed before but was changed in commit e9abd5236214cb7f29055ef12ad2defabe620180.


Another solution would be to avoid passing the vector<Partition> as parameter to the async function and add a capture to the lamba function.

So your function 

```java
auto part::getKminus1Metric(const std::vector<Partition>& partitions,
                            std::size_t edges_in_graph)
    -> std::future<std::size_t>
{
    return std::async(std::launch::async,
                      [](auto&& partitions,
                         auto edges_in_graph)
                          -> std::size_t {
                          return std::accumulate(std::cbegin(partitions),
                                                 std::cend(partitions),
                                                 0,
                                                 [](auto init, auto&& part) {
                                                     return init + part.getEdges().size();
                                                 })
                              - edges_in_graph;
                      },
                      std::cref(partitions),
                      edges_in_graph);
}
```

would become something like:

```java
auto part::getKminus1Metric(const std::vector<Partition>& partitions,
                            std::size_t edges_in_graph)
    -> std::future<std::size_t>
{
    return std::async(std::launch::async,
                      [&partitions, edges_in_graph]()
                          -> std::size_t {
                          return std::accumulate(std::cbegin(partitions),
                                                 std::cend(partitions),
                                                 0,
                                                 [](auto init, auto&& part) {
                                                     return init + part.getEdges().size();
                                                 })
                              - edges_in_graph;
                      });
}
```

This version should then work in both worlds... This is the same approach you used in part::Partition::externalDegree (with a capture instead of a constant wrapped_reference).

**Comment by DarkWingMcQuack** [comment]
Done

**Comment by ciaccia** [comment]
Hi @DarkWingMcQuack,
Excuse please me for all my remarks, this is very likely the last one. I am not a C++ expert, but according to my limited knowledge one line in your last commit is _dangerous_:

https://github.com/mayerrn/HYPE/blob/358fd08c105355e1206504119ae952f8ff69d83b/src/Partitioning.cpp#L169

The second captured parameter `edges_in_graph` is captured by reference despite having a local scope. In case the async code gets executed after the method is returned, the lambda function could point to a non existing reference (see [Dangling reference](https://en.cppreference.com/w/cpp/language/lambda) here).

Probably the safest way for avoiding such a problematic situation would be to copy the second captured parameter `by value`:

```java
 [&partitions, edges_in_graph]() 
```

Hopefully you don't get annoyed by all my comments 😉

**Comment by DarkWingMcQuack** [comment]
you are 100% right, thats UB. Thank you for pointing out, I fixed it. If you find more to fix, please let me know, or feel free to open pull requests.
