### ISSUE TITLE
A vertex gets lost when partitioning a graph in two

### ISSUE THREAD

**Issue by ciaccia** [mayerrn/HYPE#6]
When I run the program attached to this incident, the vertex 14 does not belong to any partition. The attached test cases prints the following:

> Partitions: 2
> vertices1 (45): {29, 41, 163, 65, 18, 53, 6, 77, 30, 138, 101, 54, 113, 66, 114, 149, 102, 150, 89, 42, 125, 78, 126, 137, 90, 1, 61,166, 25, 13, 85, 109, 165, 167, 73, 49, 164, 133, 97, 121, 168, 145, 157, 37, 169, }
> vertices2 (45): {160, 161, 162, 2, 26, 39, 86, 3, 50, 38, 62, 15, 63, 110, 16, 51, 98, 4, 27, 74, 99, 146, 52, 5, 122, 28, 75, 147, 100, 111, 158, 17, 64, 136, 134, 87, 40, 123, 76, 88, 135, 159, 112, 124, 148, }
> 

As you can see, the vertex 14 gets lost and does not belong to any partition.

[hype_bug.txt](https://github.com/mayerrn/HYPE/files/2696825/hype_bug.txt)

**Comment by DarkWingMcQuack** [comment]
Thanks for this issue, I have not forgotten about it and will come back and fix it when I have some more time.

**Comment by DarkWingMcQuack** [comment]
Hey @ciaccia I build the hype_bug.txt you linked there and executed the file.
I get a totaly different output than you:

```
Partitions: 2
vertices1 (45): {110, 134, 146, 122, 125, 137, 149, 29, 42, 121, 158, 160, 49, 161, 13, 166, 167, 165, 133, 54, 90, 61, 163, 126, 162, 18, 97, 73, 159, 1, 25, 37, 109, 30, 150, 138, 114, 102, 157, 78, 85, 164, 6, 145, 66, }
vertices2 (45): {169, 40, 53, 51, 52, 64, 63, 39, 3, 74, 111, 148, 112, 38, 75, 65, 28, 41, 4, 62, 99, 136, 147, 113, 2, 76, 124, 50, 87, 5, 123, 86, 89, 15, 77, 135, 98, 101, 27, 26, 100, 14, 88, 17, 16, }
```
As you can see node `14` appears to be in partition 2. Nevertheless something is wrong there, because the actual number of nodes should be `91`, so i guess another node is missing.
Could you tell me which compiler you used to build HYPE and could you rebuild and run the hype_bug.txt file you linked in the issue to see if we get the same outputs.
Greetings and sorry for the long waiting time.

**Comment by DarkWingMcQuack** [comment]
The actual problem was the following line:
```
const auto delta = graph.getVertices().size()
/ number_of_partitions;
```
When the number of vertices is not divisible by the number of partitions, then due to integer division `delta * number of partitions` does not result in the number of vertices.
A quick fix for this, is to change that line to:
```
const auto delta = graph.getVertices().size()
/ number_of_partitions + 1;
```

**Comment by ciaccia** [comment]
Hi @DarkWingMcQuack,
I think your fix breaks the existing correct logic when the number of nodes is divisible by the number of partitions... You should use a `ceil` function, in order to keep the correct delta when the remainder is zero.

Delta should be computed as following:
delta = (num_of_vertices + number_of_partitions - 1)  / number_of_partitions

As described here: https://stackoverflow.com/a/2745086

This should work as long the two values are both positive.

**Comment by DarkWingMcQuack** [comment]
@ciaccia you are 100% right. I now used the `ceil` function you proposed.

**Comment by ciaccia** [comment]
Hallo @DarkWingMcQuack,
I have noticed another minor issue... The `ceil` fix solves one issue but not all.

Consider the following example: 91 nodes, 10 partitions. The current code fills the first 9 partitions with 10 nodes each and the last partition contains just 1 node. Ideally in this case the first partition should have 10 nodes and the last 9 should have 9 nodes each. I don't know if my example is clear enough...

In order to fix this we must first compute how many "full" partitions are present, and then fill the remaining ones with one node less.
```
    const auto delta = graph.getVertices().size() / number_of_partitions; // truncated
    const auto full_partitions = graph.getVertices().size() - number_of_partitions*delta;
```

and then inside the loop 
```
    //helper function to check if the partition is full
    auto is_partition_full = [&delta, &full_partitions](std::size_t index, auto&& partition) {
        if (index < full_partitions) {
            return partition.numberOfNodes() >= delta + 1; 
        } else {
            return partition.numberOfNodes() >= delta;
        } 
    }; 

    while(!is_partition_full(i, part)
```

Note: In case the number of nodes is divisible by number_of_partitions (for example 90 nodes and 10 partitions), `full_partitions` is equal to 0 and `delta` contains the correct value.

**Comment by DarkWingMcQuack** [comment]
You are right, currently the nodes are getting added greedily to partitions and the last partition only holds `n mod m` nodes when partitioning a graph of `n` nodes into `m` partitions. SInce applying this change would result in totaly different partitionings than the current version of HYPE, I have to talk with my colleagues if we will merge this change into `master`. If you want to, feel free to provide this change as a pull request.
Greetings DarkWingMcQuach

**Comment by ciaccia** [comment]
Hi @DarkWingMcQuack,
I have just created the pull request.

I have just read your HYPE paper again, and it just says:

> The  default  balancing  objective  of  the  HYPE  algorithm leads to a balanced number of vertices on each partition. For n vertices and k partitions, the algorithm repeats the neighbor-hood  expansion,  one  vertex  at  a  time,  until  there  are  exactly max=n/k vertices  per partition.

I don't think the paper explicitly says that only the last partition can contain less nodes.
